### ISSUE TITLE
No dynamic lights showing

### ISSUE THREAD

**Issue by BrainStone** [BluePaint2/Forge.Dynamic-1.19.2#1] opened 2022-09-19 00:43 UTC
I tried out the mod and sadly no dynamic lights show up

Using version 1.19.2-1.0.0

**Comment by Spadgerr** [comment] 2022-09-29 06:03
Having this same issue, using alongside rubidium.

**Comment by BluePaint2** [comment] 2022-10-05 21:57
Are there any other mods you are using as well?

**Comment by thimblebird** [comment] 2022-10-06 19:12
It is indeed caused by [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) (`rubidium-0.6.2.jar`):

without Rubidium:
![2022-10-06_21 04 22](https://user-images.githubusercontent.com/93487547/194398442-6f1d6dab-4951-43ab-adfe-a772f2748859.png)

with Rubidium:
![2022-10-06_21 06 09](https://user-images.githubusercontent.com/93487547/194398461-115cfbdd-7162-4433-b69e-66b12d1ae0f8.png)

The dropped item itself is illuminated, same as holding the item in the hand. Just no dynamic lighting in the world.

**Comment by BluePaint2** [comment] 2022-10-08 02:00
interesting, ill take a look into that

**Comment by BluePaint2** [comment] 2022-10-08 16:54
Ive taken a look at how rubidium handles shaders, and I created a resource pack that makes solid blocks have no color.

without Rubidium:
![2022-10-08_12 48 42](https://user-images.githubusercontent.com/112736544/194718593-9f0fb1be-c621-4955-98e7-df3d62ef0cfa.png)

with Rubidium:
![2022-10-08_12 50 33](https://user-images.githubusercontent.com/112736544/194718596-e9a19aaf-313c-4c0a-af80-45c812374154.png)

It seems as though rubidium doesn't allow block shaders to be changed, hence why they have no lighting.  Unfortunately this issue is out of my control and would have to be fixed by the rubidium/sodium dev.

If you would like to test the resource pack yourself, you can do so here
[Black Block Back -- 1.19.2.zip](https://github.com/BluePaint2/Blue-Dynamic-Lights/files/9739824/Black.Block.Back.--.1.19.2.zip)

**Closed as not planned by BluePaint2** 2022-10-08 16:54 UTC
